version: '3.7'
services:

  postgres:
    image: postgres:9.6.18-alpine
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - 5432:5432
    volumes:
      - ./conf/pg-init.sql:/docker-entrypoint-initdb.d/pg-init.sql
      - ./data/pg-data:/var/lib/postgresql/data

  redis:
    image: redis:5-alpine
    restart: unless-stopped

  minio:
    image: minio/minio:RELEASE.2020-06-22T03-12-50Z
    entrypoint: sh
    command: -c 'mkdir -p /data/hive && /usr/bin/minio server /data' # Create bucket "hive" and start server
    volumes:
      - ./data/minio-data:/data
    environment:
      - MINIO_ACCESS_KEY
      - MINIO_SECRET_KEY
    ports:
      - 9000:9000

  metastore:
    image: shivarajugowda/hivemetastore:3.0.0
    environment:
      - INIT_SCHEMA
      - HIVE_METASTORE_PORT
      - HIVE_METASTORE_URI
      - HIVE_METASTORE_JDBC_URL
      - HIVE_METASTORE_DRIVER
      - HIVE_METASTORE_USER
      - HIVE_METASTORE_PASSWORD
      - S3_ENDPOINT
      - S3_ACCESS_KEY
      - S3_SECRET_KEY
      - S3_HIVE_WAREHOUSE_DIR

  presto:
    image: prestosql/presto:337
    volumes:
      - ./conf/hive.properties:/usr/lib/presto/default/etc/catalog/hive.properties
    command: /usr/lib/presto/bin/run-presto  -Dhive.metastore.uri="$HIVE_METASTORE_URI" -Dhive.s3.aws-access-key="$S3_ACCESS_KEY" -Dhive.s3.aws-secret-key="$S3_SECRET_KEY" -Dhive.s3.endpoint="$S3_ENDPOINT"
    ports:
      - 8080:8080
    logging:
      driver: none

  redash-server:
    image: redash/redash:9.0.0-beta.b42121
    command: server
    depends_on:
      - postgres
      - redis
    ports:
      - 5000:5000
      - 5678:5678
    environment:
      - REDASH_LOG_LEVEL
      - REDASH_REDIS_URL
      - REDASH_DATABASE_URL
      - REDASH_RATELIMIT_ENABLED
      - PYTHONUNBUFFERED

  redash-scheduler:
    image: redash/redash:9.0.0-beta.b42121
    command: scheduler
    depends_on:
      - redash-server
    environment:
      - REDASH_LOG_LEVEL
      - REDASH_REDIS_URL
      - REDASH_DATABASE_URL
      - REDASH_RATELIMIT_ENABLED

  redash-worker:
    image: redash/redash:9.0.0-beta.b42121
    command: worker
    depends_on:
      - redash-server
    environment:
      - REDASH_LOG_LEVEL
      - REDASH_REDIS_URL
      - REDASH_DATABASE_URL
      - REDASH_RATELIMIT_ENABLED
      - PYTHONUNBUFFERED