version: '3.7'
services:

  postgres:
    image: postgres:9.6.18-alpine
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - 5432:5432

  minio:
    image: minio/minio:RELEASE.2020-06-22T03-12-50Z
    entrypoint: sh
    command: -c 'mkdir -p /data/hive && /usr/bin/minio server /data' # Create bucket "hive" and start server
    environment:
      - MINIO_ACCESS_KEY
      - MINIO_SECRET_KEY
    ports:
      - 9000:9000

  metastore:
    image: shivarajugowda/hivemetastore:3.0.0
    environment:
      - HIVE_METASTORE_JDBC_URL
      - HIVE_METASTORE_DRIVER
      - HIVE_METASTORE_USER
      - HIVE_METASTORE_PASSWORD
      - S3_ENDPOINT
      - S3_ACCESS_KEY
      - S3_SECRET_KEY
      - S3_HIVE_WAREHOUSE_DIR

  presto:
    image: prestosql/presto:337
    volumes:
      - ./conf/hive.properties:/usr/lib/presto/default/etc/catalog/hive.properties
    command: /usr/lib/presto/bin/run-presto  -Dhive.metastore.uri="$HIVE_METASTORE_URI" -Dhive.s3.aws-access-key="$S3_ACCESS_KEY" -Dhive.s3.aws-secret-key="$S3_SECRET_KEY" -Dhive.s3.endpoint="$S3_ENDPOINT"
    ports:
      - 8080:8080
#    logging:
#      driver: none